---
# tasks file for install_docker

- name: Install docker dependencies
  apt: name={{item}} state=latest
  with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - libnss-mdns
  become: yes

- name: add docker apt key
  raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  become: yes

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker
  become: yes

- name: install docker-ce
  apt: 
    name: docker-ce={{docker_version}}
    state: present
  become: yes

- name: hold docker
  raw: apt-mark hold docker-ce
  become: yes

- name: add user to docker group
  raw: usermod -a -G docker ubuntu
  become: yes

