---
# tasks file for cluster-ingest
- name: install haproxy
  apt: 
    name: haproxy
    state: present
  become: yes

- template:
    src: ../files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  become: yes

- name: restart haproxy
  systemd:
    state: restarted
    daemon_reload: yes
    name: haproxy
  become: yes

