---

- template:
    src: ../files/weavescope_ns_default.yaml
    dest: /home/ubuntu/weavescope.yaml

- name: deploy weavescope to kubernetes
  raw: kubectl create -f /home/ubuntu/weavescope.yaml

- name: deploy docker registry on master
  raw: docker run -d -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 -p 5000:5000 --name registry registry:2 --restart


